const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

module.exports = async ({browser,pageFor,open,screenshot,base,output}) => {
  for (const [width,theme] of [[1440,'light'],[390,'dark']]) {
    const page = await pageFor(browser,width,theme);
    await open(page,'attendance');
    await page.fill('#attendanceCode','incorrect');
    await page.click('#attendanceCheckInButton');
    await page.waitForFunction(()=>document.querySelector('#attendanceCheckInStatus').textContent.includes('Incorrect'));
    assert.equal(await page.locator('#attendanceSuccessDialog').evaluate(e=>e.open),false);
    await page.fill('#attendanceCode','test-code');
    await page.click('#attendanceCheckInButton');
    await page.waitForSelector('#attendanceSuccessDialog[open]');
    assert.match(await page.locator('#attendanceSuccessTitle').innerText(),/checked in/i);
    await screenshot(page,`attendance-confirmation-${width}-${theme}`);
    await page.click('#attendanceSuccessDone');
    await page.fill('#attendanceCode','test-code');
    await page.click('#attendanceCheckInButton');
    await page.waitForSelector('#attendanceSuccessDialog[open]');
    assert.equal(await page.locator('#attendanceSuccessTitle').innerText(),'Already checked in');
    assert.equal(await page.evaluate(()=>window.__testData.records.length),1);
    assert.equal(await page.evaluate(()=>window.__calls.filter(c=>c.action==='attendanceBootstrap').length),1);
    await page.click('#attendanceSuccessDone');
    await page.click('#attendanceManageOpen');
    await page.fill('#attendanceAdminPassword','incorrect');
    await page.click('#attendanceAdminLoginButton');
    await page.waitForFunction(()=>document.querySelector('#attendanceAdminLoginStatus').textContent.includes('Incorrect'));
    await page.fill('#attendanceAdminPassword','test-admin');
    await page.click('#attendanceAdminLoginButton');
    await page.waitForSelector('#attendanceAdminWorkspace:not(.is-hidden)');
    await page.click('[data-attendance-edit="MEET-1"]');
    await screenshot(page,`attendance-officer-${width}-${theme}`);
    assert.equal(await page.locator('#attendanceAdminDialog').evaluate(e=>e.scrollWidth<=e.clientWidth+2),true);
    await page.fill('#attendanceMeetingTitle','Updated weekly meeting');
    await page.fill('#attendanceMeetingNotes','Bring project updates.');
    await page.click('#attendanceMeetingSave');
    await page.waitForFunction(()=>document.querySelector('#attendanceMeetingFormStatus').textContent.includes('saved.'));
    const saved = await page.evaluate(()=>window.__calls.filter(c=>c.action==='attendanceSaveMeeting').at(-1).payload);
    assert.equal(saved.id,'MEET-1'); assert.equal(saved.code,''); assert.equal(saved.teamId,'TEAM-CLUB');
    assert.equal(saved.startTime,'18:00'); assert.equal(saved.endTime,'19:00'); assert.equal(saved.location,'Engineering lab');
    await page.click('[data-attendance-roster="MEET-1"]');
    assert.equal(await page.locator('.attendance-roster-name strong').innerText(),'Jordan Lee');
    await screenshot(page,`attendance-roster-${width}-${theme}`);
    const downloadPromise = page.waitForEvent('download');
    await page.click('#attendanceRosterCsv');
    const download = await downloadPromise;
    const csvPath = path.join(output,`attendance-${width}.csv`); await download.saveAs(csvPath);
    const csv=fs.readFileSync(csvPath,'utf8');
    assert.match(csv,/Meeting,Date,Member,Checked in at/);assert.match(csv,/Updated weekly meeting/);assert.match(csv,/Jordan Lee/);
    page.on('dialog',d=>d.accept());
    await page.click('[data-record-remove]');
    await page.waitForFunction(()=>window.__testData.records.length===0);
    await page.waitForFunction(()=>document.querySelector('#attendanceRosterList').textContent.includes('No check-ins yet'));
    await page.click('#attendanceNewMeeting');
    await page.fill('#attendanceMeetingTitle','Officer test meeting');
    await page.fill('#attendanceMeetingCode','new-password');
    await page.click('#attendanceMeetingSave');
    await page.waitForFunction(()=>document.querySelector('#attendanceMeetingFormStatus').textContent.includes('saved.'));
    assert.equal(await page.inputValue('#attendanceMeetingId'),'MEET-NEW');
    await page.uncheck('#attendanceMeetingActive');await page.click('#attendanceMeetingSave');
    await page.waitForFunction(()=>document.querySelector('#attendanceMeetingFormStatus').textContent.includes('closed.'));
    assert.equal(await page.locator('#attendanceMeeting option[value="MEET-NEW"]').count(),0);
    await page.click('#attendanceMeetingArchive');
    await page.waitForFunction(()=>window.__testData.meetings.find(m=>m.id==='MEET-NEW').archived);
    assert.equal(await page.evaluate(()=>window.__testData.meetings.length),2);
    await page.click('[data-attendance-edit="MEET-NEW"]');await page.check('#attendanceMeetingActive');await page.click('#attendanceMeetingSave');
    await page.waitForFunction(()=>document.querySelector('#attendanceMeetingFormStatus').textContent.includes('saved.'));
    assert.equal(await page.locator('#attendanceMeeting option[value="MEET-NEW"]').count(),1);
    assert.equal(await page.locator('#attendanceAdminWorkspace a[href="admin.html#attendance"]').count(),1);
    await page.click('#attendanceAdminLogout');
    assert.equal(await page.locator('#attendanceAdminLogin').isVisible(),true);
    assert.equal(await page.evaluate(()=>sessionStorage.getItem('asmeAttendanceAdminToken')),null);
    await page.goto(`${base}/attendance-admin.html`);await page.waitForURL('**/admin.html#attendance');
    const adminUrl=new URL(await page.locator('#adminDashboardLink').getAttribute('href'));
    assert.equal(adminUrl.hash,'#attendance');assert.equal(adminUrl.searchParams.get('view'),'admin');
    await page.context().close();
  }
  // A meeting link selects once; background refreshes keep the member's later choice.
  const linked=await pageFor(browser,390);
  await linked.addInitScript(()=>localStorage.setItem('asmeAttendancePublicCacheV21',JSON.stringify({savedAt:Date.now(),data:{teams:[],meetings:[{id:'MEET-1',title:'Linked meeting',meetingDate:'2026-09-16',active:true},{id:'MEET-2',title:'Second meeting',meetingDate:'2026-09-16',active:true}]}})));
  await linked.goto(`${base}/attendance.html?meeting=MEET-1`);
  await linked.evaluate(()=>{window.__testData.meetings.push({...window.__testData.meetings[0],id:'MEET-2',title:'Second meeting'});const original=Date.now;Date.now=()=>original()+120000;document.dispatchEvent(new Event('visibilitychange'));});
  await linked.waitForSelector('#attendanceMeeting option[value="MEET-2"]',{state:'attached'});
  await linked.selectOption('#attendanceMeeting','MEET-2');
  await linked.evaluate(()=>{const original=Date.now;Date.now=()=>original()+120000;document.dispatchEvent(new Event('visibilitychange'));});
  await linked.waitForTimeout(100);assert.equal(await linked.inputValue('#attendanceMeeting'),'MEET-2');
  // Officer editing retains a team that is absent from the currently active team list.
  await linked.evaluate(()=>{window.__testData.meetings[0].teamId='OLD-TEAM';window.__testData.meetings[0].teamName='Previous team';});
  await linked.click('#attendanceManageOpen');await linked.fill('#attendanceAdminPassword','test-admin');await linked.click('#attendanceAdminLoginButton');await linked.waitForSelector('[data-attendance-edit="MEET-1"]');await linked.click('[data-attendance-edit="MEET-1"]');
  assert.equal(await linked.inputValue('#attendanceMeetingTeam'),'OLD-TEAM');
  await linked.click('#attendanceMeetingSave');await linked.waitForFunction(()=>document.querySelector('#attendanceMeetingFormStatus').textContent.includes('saved.'));
  assert.equal(await linked.evaluate(()=>window.__calls.filter(c=>c.action==='attendanceSaveMeeting').at(-1).payload.teamId),'OLD-TEAM');
  await linked.context().close();
  // A cold-start outage produces an actionable error without an unhandled rejection.
  const offline=await pageFor(browser,390);await offline.addInitScript(()=>{window.__attendanceOffline=true});await open(offline,'attendance');assert.match(await offline.locator('#attendanceConnectionBanner').innerText(),/Service unavailable/);await offline.context().close();
  console.log('Attendance: password errors, confirmation, duplicate check-in, meeting edit/create/close/archive/restore, roster removal/CSV, logout, analytics links, selection retention, older teams, service outage.');
};
