const assert = require('node:assert/strict'), fs = require('node:fs');
const C = require('../assets/reels/core.js'), makeBackend = require('./reels-backend-fixture.cjs');
const video = 'AbC_123xy-Z';
for (const link of [`https://youtube.com/shorts/${video}?si=abc`,`https://m.youtube.com/shorts/${video}/`,`https://youtu.be/${video}?t=2`,`https://www.youtube.com/watch?v=${video}&t=2`,`youtube.com/shorts/${video}`]) assert.equal(C.videoId(link), video);
for (const link of ['javascript:alert(1)',`https://youtube.com.evil.test/shorts/${video}`,`https://youtube.com@evil.test/shorts/${video}`,`https://evil.test/youtube.com/shorts/${video}`,`https://youtube.com/watch?v=${video}&v=AbC_123xy-Y`,`https://youtube.com/shorts/${video}bad`,`https://youtube.com:443/shorts/${video}`,`https://youtu.be/${video}/more`,'https://youtube.com/playlist?list=abc']) assert.throws(()=>C.videoId(link),link);
assert.equal(C.nameKey('  JoRDAN   Lee '),'jordan lee'); assert.equal(C.nameKey('Jose\u0301 Lee'),C.nameKey('José Lee'));
assert.throws(()=>C.name('<script>'));
const b = makeBackend(), s = b.context;
const preserved = [...b.sheets].filter(([n])=>!n.startsWith('Reels ')).map(([n,v])=>[n,JSON.stringify(v.rows)]);
const posts = b.sheets.get('Reels Posts'); posts.rows[0].push('officer notes'); posts.rows[0].reverse();
const post = s.reelsSubmit_({name:'Jordan Lee',url:`https://youtube.com/shorts/${video}`,title:'Battery test',caption:'=SUM(1,2)',category:'karting'}).item;
assert.equal(post.id,'REEL-'+video); assert.equal(post.caption,'=SUM(1,2)');
assert(posts.rows[1].includes("'=SUM(1,2)"));
assert.equal(s.reelsSubmit_({name:'Other Member',url:`https://youtu.be/${video}`,title:'Different caption'}).duplicate,true);
assert.equal(s.reelsRows_('Posts').length,1);
assert.equal(s.reelsFeed_({}).items[0].title,'Battery test');
s.reelsSave_({name:'Jordan Lee',reelId:post.id,active:'true'});
s.reelsSave_({name:' JORDAN   lee ',reelId:post.id,active:'true'});
assert.equal(s.reelsRows_('Saves').length,1);assert.equal(s.reelsSaved_({name:'jordan lee'}).items.length,1);
assert.equal(s.reelsSaved_({name:'Other Member'}).items.length,0);
s.reelsSave_({name:'Jordan Lee',reelId:post.id,active:'false'});assert.equal(s.reelsSaved_({name:'Jordan Lee'}).items.length,0);
const send = {name:'Jordan Lee',peer:'Casey Morgan',body:'Take a look',reelId:post.id,requestId:'1'.repeat(32)};
const sent = s.reelsSend_(send);assert.equal(sent.duplicate,false);assert.equal(s.reelsSend_(send).duplicate,true);
assert.throws(()=>s.reelsSend_({...send,body:'Changed'}),/different contents/);
assert.throws(()=>s.reelsSend_({...send,peer:' JORDAN  lee '}),/another member/);
assert.equal(s.reelsInbox_({name:'casey morgan'}).conversations[0].unread,1);
assert.match(s.reelsInbox_({name:'Casey Morgan'}).notice,/not private/);
assert.equal(s.reelsInbox_({name:'Unrelated Person'}).conversations.length,0);
const thread=s.reelsThread_({name:'Casey Morgan',peer:'Jordan Lee',markRead:'true'});assert.equal(thread.messages[0].reel.id,post.id);
assert.equal(s.reelsInbox_({name:'Casey Morgan'}).conversations[0].unread,0);
// Historical pages and read positions do not overwrite the newest receipt.
for(let i=0;i<70;i++)s.reelsWrite_('Messages',{id:'history-'+String(i).padStart(3,'0'),fromName:'Jordan Lee',fromKey:'jordan lee',toName:'Casey Morgan',toKey:'casey morgan',body:'Old '+i,reelId:'',createdAt:new Date(Date.UTC(2025,0,1,0,i)).toISOString()});
const newest=s.reelsThread_({name:'Casey Morgan',peer:'Jordan Lee',markRead:'true'});assert.equal(newest.messages.length,50);assert(newest.before);
const older=s.reelsThread_({name:'Casey Morgan',peer:'Jordan Lee',before:newest.before,markRead:'true'});assert.equal(older.messages.length,21);assert.equal(older.before,'');
assert.equal(s.reelsInbox_({name:'Casey Morgan'}).conversations[0].unread,0);
// Removed reels are no longer playable in Saved or in old messages.
s.reelsWrite_('Posts',{hidden:'true'},s.reelsRows_('Posts')[0]);assert.equal(s.reelsFeed_({}).items.length,0);
assert.equal(s.reelsThread_({name:'Casey Morgan',peer:'Jordan Lee'}).messages.at(-1).reel,null);
assert.throws(()=>s.reelsSubmit_({name:'Jordan Lee',url:C.url(video)}),/removed/);
s.reelsWrite_('Posts',{hidden:'false'},s.reelsRows_('Posts')[0]);
for(let i=0;i<55;i++)s.reelsWrite_('Posts',{id:'REEL-'+String(i).padStart(11,'0'),videoId:String(i).padStart(11,'0'),title:'Reel '+i,caption:'',category:i%3?'karting':'community',author:'Seed Member',authorKey:'seed member',createdAt:new Date(Date.UTC(2025,0,1,0,i)).toISOString(),hidden:'false'});
const page1=s.reelsFeed_({}),page2=s.reelsFeed_({after:page1.next}),page3=s.reelsFeed_({after:page2.next});
assert.equal(page1.items.length,24);assert.equal(new Set([...page1.items,...page2.items,...page3.items].map(r=>r.id)).size,56);assert.equal(page3.next,'');
assert(s.reelsFeed_({filter:'karting'}).items.every(r=>r.category==='karting'));
assert.equal(s.reelsFeed_({id:post.id}).items[0].id,post.id);
assert.throws(()=>s.reelsFeed_({after:'removed'}),/Refresh/);
assert.match(b.get({action:'reelsFeed',origin:'https://bad.example'}),/not allowed/);
assert.equal(b.get({action:'reelsFeed',callback:'alert(1)'}),'Invalid callback');
assert.match(b.post({action:'reelsSend',...send,requestId:'2'.repeat(32),body:'</script><script>alert(1)</script>'}),/\\u003c/);
assert(!b.post({action:'reelsSaved',name:'Jordan Lee',origin:'https://bad.example'}).includes('"ok":true'));
assert.equal(s.asmeReelsGet_({parameter:{view:'admin'}}),null);assert.equal(s.asmeReelsGet_({parameter:{feed:'calendar'}}),null);
for(const action of b.legacyActions)assert.match(b.post({action}),new RegExp('"legacy":"'+action+'"'));
s.setupReels(); assert.equal(s.reelsRows_('Posts').length,56);
for(const [name,rows]of preserved)assert.equal(JSON.stringify(b.sheets.get(name).rows),rows,`Preserved ${name}`);
// Known duplicate columns fail before missing tables are created.
const broken=makeBackend();broken.sheets.delete('Reels Saves');broken.sheets.get('Reels Posts').rows[0].push('id');
assert.throws(()=>broken.context.setupReels(),/duplicate/);assert.equal(broken.sheets.has('Reels Saves'),false);
const limited=makeBackend(),ls=limited.context;
for(let i=0;i<10;i++)ls.reelsSubmit_({name:'Frequent Poster',url:C.url(String(i).padStart(11,'0')),title:'Club clip '+i});
assert.throws(()=>ls.reelsSubmit_({name:'Frequent Poster',url:C.url('AbC_123xy-Z'),title:'One more'}),/limit/);
for(let i=0;i<60;i++)ls.reelsSend_({name:'Frequent Sender',peer:'Recipient Name',body:'Message '+i,requestId:i.toString(16).padStart(32,'0')});
assert.throws(()=>ls.reelsSend_({name:'Frequent Sender',peer:'Recipient Name',body:'Over limit',requestId:'f'.repeat(32)}),/limit/);
assert.equal(new Set(ls.reelsRows_('Messages').map(m=>m.createdAt)).size,60,'Read positions distinguish messages sent in the same millisecond');
const built='// Generated by node reels-backend/build.cjs. Paste this whole file into Reels.gs.\n'+['assets/reels/core.js','reels-backend/service.gs'].map(f=>fs.readFileSync(f,'utf8')).join('\n');
assert.equal(fs.readFileSync('reels-backend/Reels.gs','utf8'),built);
console.log('PASS: YouTube URLs, shared saves, name-only inboxes, idempotent messages, read receipts, history, feed pages, and existing Sheet/routes preserved.');
