const fs = require('node:fs'), path = require('node:path');
const root = path.resolve(__dirname, '..');
const files = ['assets/reels/core.js', 'reels-backend/service.gs', 'reels-backend/discovery.gs'];
fs.writeFileSync(path.join(__dirname, 'Reels.gs'), '// Generated by node reels-backend/build.cjs. Paste this whole file into Reels.gs.\n' + files.map(f => fs.readFileSync(path.join(root, f), 'utf8')).join('\n'));
console.log('Built Reels.gs');
