// Rebuild the Apps Script extension from the tested shared game rules.
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const source = fs.readFileSync(path.join(root, 'assets/games/core.js'), 'utf8');
const body = source
  .split('/* GAME_CORE_START */')[1]
  .split('/* GAME_CORE_END */')[0];
const service = fs.readFileSync(path.join(__dirname, 'service.gs'), 'utf8');
fs.writeFileSync(
  path.join(__dirname, 'Games.gs'),
  '// Generated by node games-backend/build.cjs. Add as Games.gs in the EXISTING SponsorFlow Apps Script project.\nvar SFGames = (function () {\n' +
    body +
    '\n})();\n\n' +
    service,
);
console.log('Built games-backend/Games.gs');
